### PR TITLE
wasm: allow custom init path/url for the wasm binary

### LINKED ISSUE #198: wasm: allow custom init path/url for the wasm binary
Hello!

I'd would like to be able to cache the WASM binary locally, yet deno_graph doesn't provide a away to init the module with a custom path/url.

### PR DESCRIPTION
**Pull request by deckchairlabs**
Fixes #198

Updated the build task in `deno.json` to use the latest wasmbuild. Builds successfully and tests pass locally.

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Comment by dsherret** [comment]
I think we'll need to update to use serde-wasm-bindgen. @deckchairlabs are you willing to update to that? Otherwise I can take it on.

**Comment by deckchairlabs** [comment]
> I think we'll need to update to use serde-wasm-bindgen. @deckchairlabs are you willing to update to that? Otherwise I can take it on.

Do you just want the dependency updated? If so I can update the PR

**Comment by dsherret** [comment]
It's ok! I updated the code so the CI would pass. Merging this now.

**Comment by deckchairlabs** [comment]
Excellent! Will await the release

**Comment by dsherret** [comment]
I just kicked one off for you. Will be available once the CI runs finish.

**Pull request merged**
