### PR TITLE
fix: Load static deps of dynamic deps as dynamic

### PR DESCRIPTION
**Pull request by nayeemrmn**
```js
// file:///foo.js (root)
await import ("file:///bar.js");

// file:///bar.js
import "file:///baz.js";

// file:///baz.js
console.log("Hello, world!");
```
Makes `file:///baz.js` load with `self.load(specifier, true)` instead of `self.load(specifier, false)`.

### CODE REVIEW

**Review by kitsonk — COMMENTED** [review]
LGTM

We need to rebuild the WASM as part of this PR though and edits to the branch aren't allowed.

**Comment by nayeemrmn** [comment]
Updated. I have allow edits checked, though.

**Comment by kitsonk** [comment]
> Updated. I have allow edits checked, though.

Ok, odd, might have been a workflow problem on my side, as I was working off a codespace and sometimes it is odd.

**Review by kitsonk — APPROVED** [review]
LGTM

**Pull request merged**
